<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="OpenEMR Suite" duration-ms="18481" started-at="2022-11-18T10:50:20Z" finished-at="2022-11-18T10:50:39Z">
    <groups>
    </groups>
    <test name="OpenEMR Test" duration-ms="12020" started-at="2022-11-18T10:50:20Z" finished-at="2022-11-18T10:50:32Z">
      <class name="com.brillio.test.LoginUITest">
        <test-method status="PASS" signature="setup(java.lang.String, java.lang.reflect.Method)[pri:0, instance:com.brillio.test.LoginUITest@1f28c152]" name="setup" is-config="true" duration-ms="10503" started-at="2022-11-18T10:50:20Z" finished-at="2022-11-18T10:50:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ch]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.brillio.test.LoginUITest.validateLoginTitle()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="validateLoginTitle()[pri:0, instance:com.brillio.test.LoginUITest@1f28c152]" name="validateLoginTitle" duration-ms="20" started-at="2022-11-18T10:50:31Z" finished-at="2022-11-18T10:50:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [OpenEMR Login] but found [502 Bad Gateway]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [OpenEMR Login] but found [502 Bad Gateway]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.brillio.test.LoginUITest.validateLoginTitle(LoginUITest.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginTitle -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:com.brillio.test.LoginUITest@1f28c152]" name="teardown" is-config="true" duration-ms="1467" started-at="2022-11-18T10:50:31Z" finished-at="2022-11-18T10:50:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validateLoginTitle status=FAILURE method=LoginUITest.validateLoginTitle()[pri:0, instance:com.brillio.test.LoginUITest@1f28c152] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.brillio.test.LoginUITest -->
    </test> <!-- OpenEMR Test -->
    <test name="OpenEMR Test2" duration-ms="6421" started-at="2022-11-18T10:50:32Z" finished-at="2022-11-18T10:50:39Z">
      <class name="com.brillio.test.LoginUITest">
        <test-method status="PASS" signature="start()[pri:0, instance:com.brillio.test.LoginUITest@4973813a]" name="start" is-config="true" duration-ms="485" started-at="2022-11-18T10:50:20Z" finished-at="2022-11-18T10:50:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="setup(java.lang.String, java.lang.reflect.Method)[pri:0, instance:com.brillio.test.LoginUITest@4973813a]" name="setup" is-config="true" duration-ms="4796" started-at="2022-11-18T10:50:32Z" finished-at="2022-11-18T10:50:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.brillio.test.LoginUITest.validateLoginTitle()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="validateLoginTitle()[pri:0, instance:com.brillio.test.LoginUITest@4973813a]" name="validateLoginTitle" duration-ms="35" started-at="2022-11-18T10:50:37Z" finished-at="2022-11-18T10:50:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [OpenEMR Login] but found [502 Bad Gateway]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [OpenEMR Login] but found [502 Bad Gateway]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.brillio.test.LoginUITest.validateLoginTitle(LoginUITest.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginTitle -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:com.brillio.test.LoginUITest@4973813a]" name="teardown" is-config="true" duration-ms="1585" started-at="2022-11-18T10:50:37Z" finished-at="2022-11-18T10:50:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validateLoginTitle status=FAILURE method=LoginUITest.validateLoginTitle()[pri:0, instance:com.brillio.test.LoginUITest@4973813a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="end()[pri:0, instance:com.brillio.test.LoginUITest@4973813a]" name="end" is-config="true" duration-ms="370" started-at="2022-11-18T10:50:39Z" finished-at="2022-11-18T10:50:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- com.brillio.test.LoginUITest -->
    </test> <!-- OpenEMR Test2 -->
  </suite> <!-- OpenEMR Suite -->
</testng-results>
